using System;
using System.Data;
using System.Windows.Forms;
using AttendanceManagementSystem.Data;
using System.Data.SQLite;

namespace AttendanceManagementSystem.Forms
{
    public partial class MarkAttendanceForm : Form
    {
        private readonly DatabaseHelper _dbHelper;
        private readonly DateTime _date;
        private DataTable _students = null!;
        private DataGridView dgvAttendance = null!;
        private Button btnSave = null!;
        private Button btnCancel = null!;
        private ComboBox cmbStatus = null!;
        private MainForm _mainForm;

        public MarkAttendanceForm(DateTime date, MainForm mainform)
        {
            InitializeComponent();
            _dbHelper = new DatabaseHelper();
            _date = date;
            _mainForm = mainform;
            LoadStudents();
            LoadExistingAttendance();
        }

        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MarkAttendanceForm));
            dgvAttendance = new DataGridView();
            btnSave = new Button();
            btnCancel = new Button();
            cmbStatus = new ComboBox();
            ((System.ComponentModel.ISupportInitialize)dgvAttendance).BeginInit();
            SuspendLayout();
            // 
            // dgvAttendance
            // 
            dgvAttendance.AllowUserToAddRows = false;
            dgvAttendance.AllowUserToDeleteRows = false;
            dgvAttendance.BackgroundColor = SystemColors.ActiveCaption;
            dgvAttendance.ColumnHeadersHeight = 29;
            dgvAttendance.Dock = DockStyle.Top;
            dgvAttendance.Location = new Point(0, 0);
            dgvAttendance.Name = "dgvAttendance";
            dgvAttendance.RowHeadersWidth = 51;
            dgvAttendance.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvAttendance.Size = new Size(699, 266);
            dgvAttendance.TabIndex = 0;
            dgvAttendance.CellContentClick += dgvAttendance_CellContentClick;
            // 
            // btnSave
            // 
            btnSave.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            btnSave.Location = new Point(120, 287);
            btnSave.Name = "btnSave";
            btnSave.Size = new Size(93, 45);
            btnSave.TabIndex = 1;
            btnSave.Text = "Save";
            btnSave.Click += btnSave_Click;
            // 
            // btnCancel
            // 
            btnCancel.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            btnCancel.Location = new Point(478, 287);
            btnCancel.Name = "btnCancel";
            btnCancel.Size = new Size(93, 45);
            btnCancel.TabIndex = 2;
            btnCancel.Text = "Cancel";
            btnCancel.Click += btnCancel_Click; 
            // 
            // cmbStatus
            // 
            cmbStatus.Location = new Point(0, 0);
            cmbStatus.Name = "cmbStatus";
            cmbStatus.Size = new Size(121, 28);
            cmbStatus.TabIndex = 0;
            // 
            // MarkAttendanceForm
            // 
            BackColor = SystemColors.ActiveCaption;
            BackgroundImage = (Image)resources.GetObject("$this.BackgroundImage");
            ClientSize = new Size(699, 363);
            Controls.Add(dgvAttendance);
            Controls.Add(btnSave);
            Controls.Add(btnCancel);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            MaximizeBox = false;
            Name = "MarkAttendanceForm";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Mark Attendance";
            ((System.ComponentModel.ISupportInitialize)dgvAttendance).EndInit();
            ResumeLayout(false);
        }

        private void LoadStudents()
        {
            var query = "SELECT StudentId, Name, RollNumber, Class FROM Students WHERE IsActive = 1 ORDER BY RollNumber";
            _students = _dbHelper.ExecuteQuery(query);

            // 👇 Add this line to include the 'Status' column in the DataTable
            _students.Columns.Add("Status", typeof(string)); // <- Required for binding to ComboBox column

            dgvAttendance.DataSource = _students;

            // Replace the autogenerated "Status" column with a ComboBox column
            var statusColumn = new DataGridViewComboBoxColumn
            {
                DataPropertyName = "Status",
                HeaderText = "Status",
                Name = "Status",
                DataSource = new string[] { "Present", "Absent"},
                FlatStyle = FlatStyle.Flat
            };

            // Remove the auto-generated status column if it already exists (optional safety)
            if (dgvAttendance.Columns.Contains("Status"))
                dgvAttendance.Columns.Remove("Status");

            dgvAttendance.Columns.Add(statusColumn);
            var studentIdColumn = dgvAttendance.Columns["StudentId"];
            if (studentIdColumn != null)
            {
                studentIdColumn.Visible = false;  // Hides the StudentId column
            }

        }

        private void LoadExistingAttendance()
        {
            var query = @"
                SELECT StudentId, Status 
                FROM Attendance 
                WHERE Date = @Date";

            var parameters = new[]
            {
                new SQLiteParameter("@Date", _date.ToString("yyyy-MM-dd"))
            };

            var existingAttendance = _dbHelper.ExecuteQuery(query, parameters);

            foreach (DataRow row in existingAttendance.Rows)
            {
                var studentId = Convert.ToInt32(row["StudentId"]);
                var status = row["Status"].ToString();

                foreach (DataGridViewRow dgvRow in dgvAttendance.Rows)
                {
                    if (Convert.ToInt32(dgvRow.Cells["StudentId"].Value) == studentId)
                    {
                        dgvRow.Cells["Status"].Value = status;
                        break;
                    }
                }
            }
        }

        private void btnSave_Click(object sender, EventArgs e)
        {
            try
            {
                // Delete existing attendance for the date
                var deleteQuery = "DELETE FROM Attendance WHERE Date = @Date";
                var deleteParameters = new[]
                {
                    new SQLiteParameter("@Date", _date.ToString("yyyy-MM-dd"))
                };
                _dbHelper.ExecuteNonQuery(deleteQuery, deleteParameters);

                // Insert new attendance records
                foreach (DataGridViewRow row in dgvAttendance.Rows)
                {
                    if (row.Cells["Status"].Value != null)
                    {
                        var insertQuery = @"
                            INSERT INTO Attendance (StudentId, Date, Status)
                            VALUES (@StudentId, @Date, @Status)";

                        var insertParameters = new[]
                        {
                            new SQLiteParameter("@StudentId", row.Cells["StudentId"].Value),
                            new SQLiteParameter("@Date", _date.ToString("yyyy-MM-dd")),
                            new SQLiteParameter("@Status", row.Cells["Status"].Value)
                        };

                        _dbHelper.ExecuteNonQuery(insertQuery, insertParameters);
                    }
                }
                _mainForm.LoadAttendanceForDate(_date);
                _mainForm.UpdateSummary();
                _mainForm.RefreshCalendar();
                this.DialogResult = DialogResult.OK;
                this.Close();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Please ensure you have marked all Students: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            this.DialogResult = DialogResult.Cancel;
            this.Close();
        }

        private void dgvAttendance_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {

        }
    }
}